set_property direction IN [get_ports {btn[0]}]
set_property direction IN [get_ports {btn[1]}]
set_property direction IN [get_ports {clk}]
set_property direction INOUT [get_ports {ja[0]}]
set_property direction INOUT [get_ports {ja[1]}]
set_property direction INOUT [get_ports {ja[2]}]
set_property direction INOUT [get_ports {ja[3]}]
set_property direction INOUT [get_ports {ja[4]}]
set_property direction INOUT [get_ports {ja[5]}]
set_property direction INOUT [get_ports {ja[6]}]
set_property direction INOUT [get_ports {ja[7]}]
set_property direction OUT [get_ports {led0_b}]
set_property direction OUT [get_ports {led0_g}]
set_property direction OUT [get_ports {led0_r}]
set_property direction OUT [get_ports {led[0]}]
set_property direction OUT [get_ports {led[1]}]
set_property direction OUT [get_ports {led[2]}]
set_property direction OUT [get_ports {led[3]}]
set_property direction INOUT [get_ports {pio1}]
set_property direction INOUT [get_ports {pio16}]
set_property direction INOUT [get_ports {pio17}]
set_property direction INOUT [get_ports {pio18}]
set_property direction INOUT [get_ports {pio19}]
set_property direction INOUT [get_ports {pio2}]
set_property direction INOUT [get_ports {pio20}]
set_property direction INOUT [get_ports {pio21}]
set_property direction INOUT [get_ports {pio22}]
set_property direction INOUT [get_ports {pio23}]
set_property direction INOUT [get_ports {pio26}]
set_property direction INOUT [get_ports {pio27}]
set_property direction INOUT [get_ports {pio28}]
set_property direction INOUT [get_ports {pio29}]
set_property direction INOUT [get_ports {pio3}]
set_property direction INOUT [get_ports {pio30}]
set_property direction INOUT [get_ports {pio31}]
set_property direction INOUT [get_ports {pio4}]
set_property direction INOUT [get_ports {pio40}]
set_property direction INOUT [get_ports {pio41}]
set_property direction INOUT [get_ports {pio42}]
set_property direction INOUT [get_ports {pio43}]
set_property direction INOUT [get_ports {pio44}]
set_property direction INOUT [get_ports {pio45}]
set_property direction INOUT [get_ports {pio46}]
set_property direction INOUT [get_ports {pio47}]
set_property direction INOUT [get_ports {pio48}]
set_property direction INOUT [get_ports {pio5}]
set_property direction INOUT [get_ports {pio6}]
set_property direction INOUT [get_ports {pio7}]
set_property direction INOUT [get_ports {pio8}]
set_property direction INOUT [get_ports {pio9}]
set_property direction IN [get_ports {uart_rx}]
set_property direction OUT [get_ports {uart_tx}]
set_property direction INOUT [get_ports {vaux12_n}]
set_property direction INOUT [get_ports {vaux12_p}]
set_property direction INOUT [get_ports {vaux5_n}]
set_property direction INOUT [get_ports {vaux5_p}]
set_property -dict {PACKAGE_PIN M9 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 83.330 -name sys_clk_pin -waveform {0.000 41.660} -add [get_ports clk]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {btn[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports led0_b]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports led0_g]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports led0_r]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {ja[0]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {ja[1]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {ja[2]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {ja[3]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {ja[4]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {ja[5]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {ja[6]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {ja[7]}]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports vaux5_p]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports vaux5_n]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports vaux12_p]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports vaux12_n]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports pio1]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports pio2]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports pio3]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports pio4]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports pio5]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports pio6]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports pio7]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports pio8]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports pio9]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports pio16]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports pio17]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports pio18]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports pio19]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports pio20]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports pio21]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports pio22]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports pio23]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports pio26]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports pio27]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports pio28]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports pio29]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports pio30]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports pio31]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports pio40]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports pio41]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports pio42]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports pio43]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports pio44]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports pio45]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports pio46]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports pio47]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports pio48]
set_property -dict {PACKAGE_PIN M9 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 83.330 -name sys_clk_pin -waveform {0.000 41.660} -add [get_ports clk]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {btn[0]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {btn[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports led0_b]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports led0_g]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports led0_r]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {ja[0]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {ja[1]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {ja[2]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {ja[3]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {ja[4]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {ja[5]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {ja[6]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {ja[7]}]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports vaux5_p]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports vaux5_n]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports vaux12_p]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports vaux12_n]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports pio1]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports pio2]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports pio3]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports pio4]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports pio5]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports pio6]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports pio7]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports pio8]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports pio9]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports pio16]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports pio17]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports pio18]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports pio19]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports pio20]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports pio21]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports pio22]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports pio23]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports pio26]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports pio27]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports pio28]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports pio29]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports pio30]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports pio31]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports pio40]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports pio41]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports pio42]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports pio43]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports pio44]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports pio45]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports pio46]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports pio47]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports pio48]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
#revert back to original instance
current_instance -quiet
